<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kd_base"
 *
 * Auto generated by Extension Builder 2015-01-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Base Distribution',
	'description' => 'A base distribution that provides a basic configuration for typo3 cms',
	'category' => 'plugin',
	'author' => 'Kevin Ditscheid',
	'author_email' => 'kevinditscheid@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.0.0-dev',
	'constraints' => array(
		'depends' => array(
			'backend' => '9.5',
			'core' => '9.5',
			'extbase' => '9.5',
			'extensionmanager' => '9.5',
			'filelist' => '9.5',
			'fluid' => '9.5',
			'frontend' => '9.5',
			'install' => '9.5',
			'recordlist' => '9.5',
			'fluid_styled_content' => '9.5',
			'belog' => '9.5',
			'beuser' => '9.5',
			'info' => '9.5',
			'linkvalidator' => '9.5',
			'lowlevel' => '9.5',
			'rte_ckeditor' => '9.5',
			'reports' => '9.5',
			'form' => '9.5',
			'setup' => '9.5',
			'sys_action' => '9.5',
			'taskcenter' => '9.5',
			'tstemplate' => '9.5',
			'viewpage' => '9.5',
            'easy_navigation' => '1.1'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);