<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "kd_base"
 *
 * Auto generated by Extension Builder 2015-01-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Base Distribution',
	'description' => 'A base distribution that provides a basic configuration for typo3 cms',
	'category' => 'plugin',
	'author' => 'Kevin Ditscheid',
	'author_email' => 'kevinditscheid@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.1.3',
	'constraints' => array(
		'depends' => array(
			'backend' => '12.0',
			'core' => '12.0',
			'extbase' => '12.0',
			'extensionmanager' => '12.0',
			'filelist' => '12.0',
			'fluid' => '12.0',
			'frontend' => '12.0',
			'install' => '12.0',
			'recordlist' => '12.0',
			'fluid_styled_content' => '12.0',
			'belog' => '12.0',
			'beuser' => '12.0',
			'info' => '12.0',
			'linkvalidator' => '12.0',
			'lowlevel' => '12.0',
			'rte_ckeditor' => '12.0',
			'reports' => '12.0',
			'form' => '12.0',
			'setup' => '12.0',
			'tstemplate' => '12.0',
			'viewpage' => '12.0',
			'easy_navigation' => '2.2'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
